### ISSUE TITLE
Repository name (and case) should match the package name (as in DESCRIPTION)

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/rSharp#11]
Difference in name leads to weird installation issues and often need extra/unregular steps to make it work, let's make our lives easier (mostly mine when setting up CI/CD pipelines 😉 ) !

Also, I would avoid upper case to make things even easier (We won't have to remember which letter is lower/uppercase).

More on naming practices: https://r-pkgs.org/workflow101.html#name-your-package

**👉 My suggestion for the name: `{sharpr}`**

**Comment by rwmcintosh** [comment]
@Felixmil are you suggesting a rename from rSharp, or RSharp to sharpr?

**Comment by Felixmil** [comment]
Yeah, or rsharp

**Comment by rwmcintosh** [comment]
We kept rSharp in the spirit of rClr
