### ISSUE TITLE
Make the header include path not version specific

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/rSharp#116]
How? IDK. But somehow this should come from an environment variable or something

**Comment by rwmcintosh** [comment]
rSharp.props has a version specific path in it which means that specific version must be installed.
The instruction is given in README.Rmd and should also be removed.

**Comment by PavelBal** [comment]
I think this must be part of the documentation. The user has to manually take care of defining the path to R installation as system variable.

**Comment by rwmcintosh** [comment]
Yeah, then we have to remove it from ```rSharp.props```
