### ISSUE TITLE
Set up gibthub actions for the R package

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#122]

**Comment by Felixmil** [comment]
- [ ] test coverage
- [ ] R CMD Check
- [ ] pkgdown

**Comment by Felixmil** [comment]
I see in README:
> Windows
> You will need the latest Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 (you can get it from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) and .NET 8 runtime (you can get it from [here](https://dotnet.microsoft.com/download/dotnet/8.0/runtime)).

Is this required for using, installing or building the package ?

**Comment by rwmcintosh** [comment]
required for using and building at least. I think also for installing if the tests are run during install. Not sure about that.

**Comment by Felixmil** [comment]
Was it also the case for rClr ? Because the github actions did not bother installing these and it was working fine. Maybe already installed in `windows-latest` images provided by GitHub ?

**Comment by rwmcintosh** [comment]
Yeah it's pre-installed, according to this file anyway
https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

![image](https://github.com/Open-Systems-Pharmacology/rSharp/assets/261477/fc197d1d-32ba-481a-ae2d-c0e0a1fa8ce0)

**Comment by PavelBal** [comment]
What about .NET 8? Also required to run (and, therefore, pass the tests and build vignettes)

**Comment by PavelBal** [comment]
Ah I see, is there.. Wow, nice
