### ISSUE TITLE
Set `main` branch as default and get rid of develop.

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/rSharp#126]
With the package release process we are using on other R repo, we only need the `main` branch and feature specific branches. With regular releases tags, there is no need for a develop branch.

Shall we align this repo to esqlabsR and parameteridentification ?

**Comment by PavelBal** [comment]
Yes. Pls do it.

**Comment by Felixmil** [comment]
To do after #139 is merged:
- [ ]  Set `main` as default
- [ ] Delete `develop` branch
- [ ] Make sure actions are triggered on `main`

**Comment by Felixmil** [comment]
⚠️⚠️⚠️
Now the default branch is `main`. Make sure your existing local branch are now synced with main.
⚠️⚠️⚠️

@rwmcintosh @PavelBal
