### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/rSharp#128]
I'm setting up R-CMD-Check actions on github and it fails on ubuntu with the following error:

```
  Running examples in ‘rSharp-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: getSexpType
  > ### Title: Get the type code for a SEXP
  > ### Aliases: getSexpType
  > 
  > ### ** Examples
  > 
  > getSexpType(1)
  Error in .External("r_get_sexp_type", sexp, PACKAGE = rSharpEnv$nativePkgName) : 
    "r_get_sexp_type" not available for .External() for package "rSharpUX"
  Calls: getSexpType
  Execution halted
```

This step passes on Windows.

Any idea why ?

**Comment by rwmcintosh** [comment]
The prebuilt binary is probably not built after r_get_sexp_type was added.

**Comment by rwmcintosh** [comment]
> The prebuilt binary is probably not built after r_get_sexp_type was added.

No, it's not that. None of these examples work in Linux.

**Comment by rwmcintosh** [comment]
The prototypes are not exported. I'll commit this fix on this branch.
