### ISSUE TITLE
Support for heterogeneous arrays

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/rSharp#18]
R vectors where the type is not the same for each element

**Comment by Ian-Du** [comment]
on the current rclr there are R tests specifically targeting this kind of arrays. so we try to keep/carry over thesame features

**Comment by rwmcintosh** [comment]
Yeah, a heterogenous vector in R is just a homogeneous object array in C#

**Comment by msevestre** [comment]
Yeah that’s clear
 but why would we want to use this. .net would not know the shape of the objects. What’s the point

**Comment by rwmcintosh** [comment]
If it becomes a blocking issue we can remove it, but I think once we have homogeneous arrays, then this becomes trivial.

**Comment by msevestre** [comment]
I am asking for the use case lol

**Comment by rwmcintosh** [comment]
I have no idea, but it was supported by the original implementer.
