### ISSUE TITLE
Set up continuous integration for C++ and C#

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/rSharp#22]
Windows and Linux

**Comment by PavelBal** [comment]
1. Build windows C++/C# libs
2. Build linux libs
3. Build R package
4. Build website

**Comment by Felixmil** [comment]
Superseded by #122 ?

**Comment by PavelBal** [comment]
One step at a time, we are not sure how to set up CI for C++/C# libs. First, lets have this running for R.

**Comment by PavelBal** [comment]
@Felixmil @Yuri05 

Right now we build the C++/C# libs locally, commit the updated DLLs, and the CI (GitHub actions) only builds the R package. Is it possible to do C++/C# building also with GA?

**Comment by PavelBal** [comment]
Related: https://github.com/Open-Systems-Pharmacology/rSharp/issues/121

**Comment by Felixmil** [comment]
I'm sure it is possible but I have no experience in building C++/C#. Though, I have enough experience to provide support for translating technical requirement (provided by Rob) to github actions/workflow.

**Comment by rwmcintosh** [comment]
It's probably no problem for the .NET assemblies, but the native dll's are a different story. We need to produce a package containing rSharpUx.so and rSharpMs.dll for Ubuntu and Windows respectively. You need both OS's to build them.
