### ISSUE TITLE
MSVCP runtime version

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#27]
During package load, the script checks if the Microsoft Vicuals C ++ runtime is found, and it does so by looking for the `msvcp140.dll`.

1. Is this still the up-to-date version of the runtime?
2. It performs the check on Windows here:
3. 
https://github.com/Open-Systems-Pharmacology/rSharp/blob/da57ab9dc1dccc1fbbaebe7783de21fa7ecde414/R/zzz.R#L4-L12

How should this be done on Linux?

**Comment by rwmcintosh** [comment]
On Linux you need to check the version of ```glibc```

I'm not sure we need to check for a specific version though, only that it's installed.

**Comment by PavelBal** [comment]
Related to https://github.com/Open-Systems-Pharmacology/rSharp/issues/52

**Comment by PavelBal** [comment]
https://github.com/Open-Systems-Pharmacology/rClr/pull/26#discussion_r1311741201

**Comment by rwmcintosh** [comment]
> 1. Is this still the up-to-date version of the runtime?

Yes, updated versions of the MSVC runtime still use the same dll name it seems We won't have to update this check
