### ISSUE TITLE
Crash when trying to get runtime version

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#32]
RStudio crashes when trying to do this:

https://github.com/Open-Systems-Pharmacology/rSharp/blob/da57ab9dc1dccc1fbbaebe7783de21fa7ecde414/R/zzz.R#L37

Null pointer?

Here how to reproduce:

```
nativePkgName <- "RsharpMs"
nativeLibrary <- "D:/Work/OSPS/Repos/rSharp/inst/lib/RsharpMs.dll"
srcPkgLibPath <- "D:/Work/OSPS/Repos/rSharp/inst/lib"

# Load C++ library
dyn.load(nativeLibrary, DLLpath = srcPkgLibPath)
# Load .NET library through C++
invisible(.C("rSharp_create_domain", srcPkgLibPath, PACKAGE = nativePkgName))

# Try to create a pointer - fail
extPtr <- .External("r_call_static_method", "Rclr.ClrFacade", "GetFieldOrProperty", "System.Environment", "Version", PACKAGE = nativePkgName)
```

**Comment by rwmcintosh** [comment]
```Rclr.ClrFacade``` is not the correct qualified class name. It should be ClrFacade.ClrFacade. Although, this is likely to change from #29

**Comment by PavelBal** [comment]
It is because ClrFacade is not found: https://github.com/Open-Systems-Pharmacology/rSharp/issues/31
