### ISSUE TITLE
`r_get_typename_externalptr` returns something strange

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#41]
```
nativePkgName <- "RsharpMs"
nativeLibrary <- "D:/Work/OSPS/Repos/rSharp/inst/lib/RsharpMs.dll"
srcPkgLibPath <- "D:/Work/OSPS/Repos/rSharp/inst/lib"

# Load C++ library
dyn.load(nativeLibrary, DLLpath = srcPkgLibPath)
# Load .NET library through C++
invisible(.C("rSharp_create_domain", srcPkgLibPath, PACKAGE = nativePkgName))

# Create a pointer to an object
testClassName <- "ClrFacade.Tests.RefClasses.LevelOneClass"
o <- .External("r_create_clr_object", testClassName, PACKAGE = nativePkgName)
# Call r_get_typename_externalptr to get the type name
.External("r_get_typename_externalptr", o, PACKAGE = nativePkgName)
```

This returns ""汃䙲捡摡\u2e65敔瑳\u2e73敒䍦慬獳獥䰮癥汥湏䍥慬獳渀㩳机瑥灏楴湯挨湯瑳挠慬獳猠摴㨺慢楳彣瑳楲杮挼慨Ⱳ瑳畲瑣猠摴㨺档牡". Expected is the type name.

**Comment by rwmcintosh** [comment]
Can you re-run this test after you get a current build?

**Comment by Yuri05** [comment]
@PavelBal I tried to translate and got this ⏬ . I wonder what you are testing 🤣 
<details><summary>Interesting</summary>
<p>

![grafik](https://github.com/Open-Systems-Pharmacology/rSharp/assets/25061876/d46af8c2-511b-45cf-b488-9a07f14b8f0f)


</p>
</details>

**Comment by rwmcintosh** [comment]
Well, IDK about the translation, but this issue was about character width conversions and I'm pretty sure it's resolved from a fix I pushed yesterday.

@PavelBal can close when he's satisfied there's nothing to do here.
