### ISSUE TITLE
Investigate skipped tests

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/rSharp#43]
There are tests in tests directory that are empty, or do not have any assertions. Those come back as 'SKIP'.

In some cases, the code is commented out, they can probably just be removed now.

In other cases, there is code, but no assertions. Those tests do have a purpose (that the system does not crash). We should find a way to remove them from 'SKIP' count and make them count.

**Comment by PavelBal** [comment]
Do you mean R tests or c++/c#?

**Comment by rwmcintosh** [comment]
R tests - anything other than 100% of all tests passing is a fail. If you can't write a test in a way that passes or fails then it should be not counted. Right now we have 3 'Skipped'.

✔ | F W S  OK | Context
✔ |     3 187 | rSharp essentials [1.1s]                                                                       
✔ |       126 | Date and times  


It appears that there are some tests where the internal asserts are commented out. In this case below, the fix is that the commented out portion should extend to the ```test_that``` until the assertion can be coded. Note that the workitem is lost to history since codeplex is long gone.

```
test_that("Garbage collection of R.NET objects", {
  # Unfortunately cannot test this yet because of http://r2clr.codeplex.com/workitem/30
  # testGarbageCollection( getObjCountMethodName = 'GetMemTestObjCounterRDotnet', createTestObjectMethodName = 'CreateMemTestObjRDotnet')
})
```

Other 'Skips' are more subtle because they have executing code in which the implied test is that the action does not crash the system.

```
test_that("Assembly loading", {
  # following not supported on Mono
  # clrLoadAssembly("System.Windows.Presentation, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
  clrLoadAssembly('System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')

  # The use of partial assembly names is discouraged; nevertheless it is supported
  clrLoadAssembly("System.Web.Services")
})
```

clrLoadAssembly does not assert anything, so the test is not a pass or fail according to the stats. So something is being 'tested' but in this case a 'Pass' is that the system does not crash. That needs to be re-written as either a pass or fail explicitly.

**Comment by PavelBal** [comment]
Fixed
