### ISSUE TITLE
Update nuget packages

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#46]
E.g. there is a newer version of R.NET on nuget.

**Comment by rwmcintosh** [comment]
We should discuss whether we want to keep maintaining the R.NET and dynamic_interop_dll projects as separate repos.

We use them together always, more repos means more package maintenance. This was done by rClr before presumable to offer greater flexibility.

If we fold everything into one solution then we don't have to create as many CI instances and nuget packages.

**Comment by PavelBal** [comment]
In theory, R.NET can be used without rSharp, i.g., to call R from .NET. However, that repo has not been maintained for over 4 years, so maybe we can also have the code integrated into rSharp.

**Comment by rwmcintosh** [comment]
We will have to maintain these two assemblies. It's just a matter how we want to do it - flexibly, or easily ;)

**Comment by PavelBal** [comment]
Up to you to decide ;)

**Comment by PavelBal** [comment]
Put the code together.

**Comment by rwmcintosh** [comment]
#120 makes this irrelevant.
