### ISSUE TITLE
Do not crash when loading workspace

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#56]
When trying to load a workspace that contains references to rClr objects in R studio, R studio crashes. See if this can be avoided.

**Comment by rwmcintosh** [comment]
I used the commands above but I don't get a fail until I try to evaluate ```testObj```

```
testObj <- newObjectFromName(rSharpEnv$testObjectTypeName, 1, 1)
save.image(file = "My_Object.RData")
#reload r
load("My_Object.RData")
devtools::load_all()
testObj
```
