### ISSUE TITLE
Clean up rSharp.sln

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#81]

**Comment by rwmcintosh** [comment]
What does this one mean?

**Comment by PavelBal** [comment]
Are all these lines relevant?

https://github.com/Open-Systems-Pharmacology/rSharp/blob/630c86e6fbabfcf3a743d4dfab6f6284877211b0/shared/rSharp.sln#L18-L35

**Comment by rwmcintosh** [comment]
Yes, I think so.

**Comment by rwmcintosh** [comment]
I'll close it for now.
