### ISSUE TITLE
Are these files used?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#82]
- [ ] create_lib.cmd
- [ ] get_monodsk.cmd
- [ ] get_msbuildpath.cmd
- [ ] get_winsdk.cmd
- [ ] makefile
- [ ] Makevars.in
- [ ] mono.def
- [ ] R.def
- [ ] rSharp-mono.def
- [ ] rSharp-win.def
- [ ] setup_vcpp.cmd
- [ ] win_cp.cmd

**Comment by rwmcintosh** [comment]
makefile and rSharp-win.def stay, the rest will go.
