### ISSUE TITLE
Code refactor - check for unused code

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#86]
R code calls the following external methods:

- r_create_clr_object
- r_call_method
- r_get_object_direct
- r_get_typename_externalptr
- r_get_sexp_type
- r_show_args
- r_call_static_method

Should be a good starting point the check all the methods if they are actually used.

**Comment by Ian-Du** [comment]
then all the methods listed and some others (like r_create_clr_object) all have uses in the R code. Should we close this?
