### ISSUE TITLE
Remove 32 bit support

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/rSharp#9]
@PavelBal @Yuri05 @msevestre @Ian-Du 

We don't need this I suppose?

**Comment by rwmcintosh** [comment]
It is de-facto removed because we only run 64 bit builds now, but we should just clean this up

**Comment by PavelBal** [comment]
There is a i386 folder here https://github.com/Open-Systems-Pharmacology/rSharp/tree/develop/shared/libfiles/i386

?

**Comment by rwmcintosh** [comment]
> There is a i386 folder here https://github.com/Open-Systems-Pharmacology/rSharp/tree/develop/shared/libfiles/i386
> 
> ?

We coincidentally found that folder this morning and removed it.
